apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.label }}
  name: {{ .Values.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.label }}
        ports:
          - containerPort: {{ .Values.applicationPort }}