apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.label }}
  name: {{ .Values.label }}
spec:
  ports:
  - port: {{ .Values.applicationPort }}
    protocol: TCP
    targetPort: {{ .Values.applicationPort }}
  selector:
    app: {{ .Values.label }}
  type: NodePort